"""
images_of settings module.

Anything that's not secret should probably go in here, as it will be common
to all clients. Anything that is, or needs to be tested elsewhere should be
set in local_settings.
"""
import logging
logging.getLogger().setLevel(logging.WARNING)

# Reddit Auth Info

USERNAME = 'username'
PASSWORD = 'password'

CLIENT_ID = 'clientid'
CLIENT_SECRET = 'clientsecret'
REDIRECT_URI = 'http://127.0.0.1:65010/authorize_callback'

# Network Information

NETWORK_NAME = "ImagesOf"
MULTIREDDIT = "ImagesOfPlaces"

DEFAULT_MODS = ['AutoModerator', 'BotWatchman']
DEFAULT_DESCRIPTION = 'An __ImagesOf__ Network Subreddit'
WIKI_PAGES = ['config/automoderator', 'toolbox']

MASTER_SUB = "ImagesOfNetwork"
# SLAVE_SUBS at bottom.

# Post Checking

EXTENSIONS = [
        r'\.jpg',
        r'\.jpeg',
        r'\.png',
        r'\.gif',
        r'\.gifv',
        r'\.apng',
        r'\.tiff',
        r'\.bmp',
        r'\.xcf',
]

DOMAINS = [
        r'500px\.com',
        r'abload\.de',
        r'cdn\.theatlantic\.com',
        r'.*\.deviantart\.com',
        r'.*\.deviantart\.net',
        r'fav\.me',
        r'.*\.fbcdn\.net',
        r'.*\.files\.wordpress\.com',
        r'flic\.kr',
        r'flickr\.com',
        r'forgifs\.com',
        r'gfycat\.com',
        r'(.*\.)?gifsoup\.com',
        r'(.*\.)?gyazo\.com',
        r'(.*\.)?imageshack\.us',
        r'imgclean\.com',
        r'(i\.)?imgur\.com',
        r'instagr\.am',
        r'instagram\.com',
        r'(cdn\.)?mediacru\.sh',
        r'(.*\.)?media\.tumblr\.com',
        r'(.*\.)?min\.us',
        r'(.*\.)?minus\.com',
        r'(.*\.)?panoramio\.com',
        r'photoburst\.net',
        r'(.*\.)?photoshelter\.com',
        r'pbs\.twimg\.com',
        r'(.*\.)?photobucket\.com',
        r'picsarus\.com',
        r'puu\.sh',
        r'scontent\.cdninstagram\.com',
        r'(.*\.)?staticflickr\.com',
        r'(.*\.)?tinypic\.com',
        r'twitpic\.com',
        r'upload.wikimedia\.org',
        r'i\.reddituploads.com',
]

# Slaves

SLAVE_SUBS = [
  {
    "name": "imagesofafghanistan",
    "search": [
      "afghanistan",
      "kabul",
      "bamyan",
      "kandahar",
      "bamyan province",
      "herat",
      "band-e amir national park",
      "jalalabad",
      "mazar-i-sharif",
      "paghman",
      "kunduz",
      "ghazni",
      "balkh",
      "baghlan province",
      "sistan",
      "bagram",
      "badghis province",
      "khost",
      "lashkar gah",
      "fayzabad",
      "maymana",
      "puli khumri",
      "sheberghan",
      "farah",
      "talogan",
      "samangan",
      "charikar",
      "mes aynak",
      "sange-e-masha",
    ],
    "whitelist": [
      "afghanistan",
      "afghanistanpics",
    ],
  },
  {
    "name": "imagesofalabama",
    "search": [
      "alabama",
      "alabami?ans?",
      "birmingham\b(al|alabama)",
      "montgomery\b(al|alabama)",
      "mobile\b(alabama|al)",
      "huntsville\b(alabama|al)",
      "tuscaloosa",
      "hoover\b(alabama|al)",
      "dothan",
      "decatur",
      "auburn",
      "madison\b(al|alabama)",
    ],
    'ignore': [
      "poppy montgomery",
    ],
    "ignore_case": [
      "al",
    ],
    "whitelist": [
      "uah",
      "florenceal",
      "uab",
      "wde",
      "auburn",
      "montgomery",
      "asms",
      "capstone",
      "mobileal",
      "tuscaloosa",
      "alabama",
      "huntsvillealabama",
      "birmingham",
      "rolltide",
    ],
  },
  {
    "name": "imagesofalaska",
    "search": [
      "alaska",
      "ak",
      "alaskans?",
      "anchorage",
      "fairbanks",
      "denali national park",
      "ketchikan",
      "skagway",
      "kenai fjords",
      "mendenhall glacier",
      "juneau",
      "eagle river",
      "badger\b(alaska|ak)",
      "knik\-fairview",
      "college\b(alaska|ak)",
      "sitka",
      "lakes\b(alaska|ak)",
      "tanaina\b(alaska|ak)",
    ],
    'ignore': [
      "malamute",
    ],
    "ignore_case": [
      "ak",
    ],
    "whitelist": [
      "alaskanporn",
      "uaa",
      "alaskabeer",
      "fairbanks",
      "kodiak",
      "anchorage",
      "uasjuneau",
      "alaska",
      "juneau",
      "yukon",
      "akgaming",
      "skagway",
    ],
    "blacklist": [
      "{'rupaulsdragrace', 'rpdrcirclejerk', 'ak47', 'airsoft', 'snackexchange'}",
    ],
  },
  {
    "name": "imagesofarizona",
    "search": [
      "arizona",
      "az",
      "arizoni?ans?",
      "grand\bcanyon",
      "phoenix\b(arizona|az)",
      "tucson",
      "mesa\b(arizona|az)",
      "chandler\b(arizona|az)",
      "glendale\b(arizona|az)",
      "scottsdale",
      "gilbert\b(arizona|az)",
      "sitka",
      "tempe",
      "peoria",
      "sedona",
      "antelope canyon",
      "havasu falls",
      "hoover dam",
      "desert botanical gard",
    ],
    'ignore': [
      "arizona (robins|tea)",
    ],
    "whitelist": [
      "coyotes",
      "azcardinals",
      "tempe",
      "suns",
      "asu",
      "arizonabeer",
      "phoenix",
      "flagstaff",
      "arizona",
      "arizonapolitics",
      "prescott",
      "nau",
      "uofarizona",
      "cochise",
      "bisbee",
      "tucson",
      "azdiamondbacks",
    ],
    "blacklist": [
      "{'themsfightinherds', 'kia', 'mylittlepony'}",
    ],
  },
  {
    "name": "imagesofarkansas",
    "search": [
      "arkansas",
      "arkansasans?",
      "hot springs national park",
      "crystal bridges museum",
      "clinton presidential center",
      "garvan woodland gardens",
      "little\brock",
      "fort\bsmith",
      "fayetteville",
      "springdale\b(arkansas|ar)",
      "jonesboro",
      "north\blittle\brock",
      "conway",
      "rogers",
      "pine\bbluff",
      "bentonville",
    ],
    'ignore': [
      "ar-",
    ],
    "whitelist": [
      "hendersonstate",
      "asu_jonesboro",
      "texarkana",
      "littlerock",
      "jonesboro",
      "conwayar",
      "fortsmith",
      "uca",
      "arkansas",
      "lyoncollege",
      "uafs",
      "razorbacks",
      "ozarka",
      "arkieoutdoors",
      "arkansasnature",
      "universityofarkansas",
      "fayetteville",
      "arkansashomeschoolers",
      "ualr",
      "uam",
    ],
    "blacklist": [
      "{'ar15'}",
    ],
  },
  {
    "name": "imagesofaustralia",
    "search": [
      "australia",
      "sydney",
      "melbourne",
      "perth",
      "brisbane",
      "gold coast",
      "cairns",
      "adelaide",
      "fraser island",
      "canberra",
      "port douglas",
      "margaret river",
      "kakadu national park",
      "hobart",
      "sunshine coast",
      "broome",
      "phillip island",
      "barossa valley",
      "byron bay",
      "launceston",
      "kangaroo island",
      "surgers paradise",
      "wollongong",
      "townsville",
      "exmouth",
      "cape tribulation",
      "blue mountains national park",
      "kuranda",
      "moreton island",
      "coffs harbour",
      "rockhampton",
      "mandurah",
      "pemberton",
      "hervey bay",
      "central coast",
      "tamworth",
      "bowen",
      "bunbury",
      "brisbane",
      "brusselton",
      "grampians national park",
      "north stradbroke island",
      "kalbarri",
      "toowoomba",
      "port arthur",
      "bundaberg",
      "geelong",
      "mount gambier",
      "port jackson",
      "sydney",
      "melbourne",
      "great ocean road",
      "bondi beach",
      "uluru",
      "great barrier reef",
      "kings park",
      "manly beach",
      "taronga zoo",
      "kakadu national park",
      "fraser island",
      "hunter region",
      "whitsunday islands?",
      "shrine of remembrance",
      "noosa national park",
      "whitehaven beach",
      "questacon",
      "lake burley griffin",
      "national gallery of victoria",
      "healesville santuary",
      "wilsons promontory",
      "sea world gold coast",
      "currumbin wildlife sanctuary",
      "grampians national park",
      "barossa valley",
      "burleigh heads",
      "daintree rainforest",
      "cape tribulation",
      "capitol theatre",
      "tamborine mountain",
      "adelaide botanic garden",
      "shelly beach",
      "mount ainsl",
    ],
    'ignore': [
      "sydney sierota",
    ],
    "whitelist": [
      "aussieriders",
      "aussiehiphop",
      "nrl",
      "brisbane",
      "sydney",
      "ausecon",
      "northqueensland",
      "koalas",
      "ausmemes",
      "paulkelly",
      "geelong",
      "australiasnow",
      "aushomebrew",
      "straya",
      "perth",
      "sydneymusic",
      "ausfreebies",
      "auselt",
      "newcastle",
      "startupsaustralia",
      "cairns",
      "modelparliament",
      "ballarat",
      "ausmotoring",
      "ausenviro",
      "austechsupport",
      "townsville",
      "melbourne",
      "r4rperth",
      "wollongong",
      "australiapics",
      "r4rsydney",
      "melbournemusic",
      "cquni",
      "australianright",
      "libertarianaustralia",
      "canberra",
      "ausfemalefashion",
      "westernaustralia",
      "australianfilm",
      "nbn",
      "modelaustralia",
      "netflixaustralia",
      "tweedshire",
      "ausstocks",
      "auspol",
      "melbtrade",
      "savethenbn",
      "australianhistory",
      "ausbeer",
      "sunshinecoast",
      "r4raustralia",
      "drugsaustralia",
      "australianpolitics",
      "fishingaustralia",
      "austpropertyponzi",
      "australia",
      "r4rbris",
      "australianev",
      "outdooraus",
      "auslaw",
      "regionalaustralia",
      "aleague",
      "ausmusic",
      "afl",
      "vego",
      "ausfinance",
      "ausguns",
      "circlejerkaustralia",
      "australianmfa",
      "australianagriculture",
      "centralcoastnsw",
      "tasmania",
      "r4rmelbourne",
      "ausmetal",
      "queensland",
      "ausbike",
      "triplej",
      "koalasgonewild",
      "goldcoast",
      "australianmilitary",
      "bluemountains",
      "australianfilmmakers",
      "australiantelevision",
      "darwinaustralia",
      "adelaide",
      "centralqueensland",
      "warrnambool",
      "hobart",
      "australiagonewild",
      "carsaustralia",
      "aufrugal",
      "ausfood",
      "doublej",
      "ausbookexchange",
      "australiarebooted",
      "ausents",
      "askanaustralian",
    ],
  },
  {
    "name": "imagesofbelgium",
    "search": [
      "belgium",
      "belgians?",
      "bruges",
      "brussels",
      "antwerp",
      "ghent",
      "li(è|e)ge",
      "dinant",
      "namur",
      "ypres",
      "mons",
      "charleroi",
      "bastogne",
      "durbuy",
      "ostend",
      "leuven",
      "bouillon",
      "waterloo",
      "middelkerke",
      "genk",
      "arlon",
      "la roche-en-ardenne",
      "mechelen",
      "blankenberge",
      "veurne",
      "stavelot",
      "malmedy",
      "vielsalm",
      "chimay",
      "verviers",
      "rochefort",
      "knokke-heist",
      "damme",
      "binche",
      "maaseik",
      "zeebrugge",
      "maasmechelen",
      "de haan",
      "de panne",
      "wavre",
      "voeren",
      "tournai",
      "oudenaarde",
      "koksijde",
      "han-sur-lesse",
      "poperinge|\bath",
      "Neufch(â|a)teau",
      "Belgian Luxembourg",
      "s(ain)?t bavo'?s cathedral",
      "ghen",
      "musical instrument museum",
      "cathedral of s(ain)?t michael",
      "atomium",
      "basilica of the holy blood",
      "manneken pis",
      "cinquantenaire",
      "plantin-moretus museum",
      "horta museum",
      "gravensteen",
      "pairi daiza",
      "flanders fields museum",
      "cathedral of our lady",
      "b(e|é)guinage",
    ],
    'ignore': [
      "brussels sprouts?",
    ],
    "ignore_case": [
      "ATH",
    ],
    "whitelist": [
      "leuven",
      "belgium",
      "gent",
      "bruges",
      "belgiumpics",
      "brussels",
    ],
  },
  {
    "name": "imagesofbelize",
    "search": [
      "belize",
      "ambergris caye",
      "caye caulker",
      "xunantunich",
      "lamanai",
      "great blue hole",
      "caracol",
      "actun tunichil muknal",
      "cockscomb basin",
      "hol chan",
      "san ignacio resort",
      "baron bliss light",
      "guanacastle national park",
      "san pedro",
      "placencia",
      "san ignacio",
      "belmopan",
      "punta gorda\b|corozal town",
      "dangriga",
      "orange walk town",
      "crooked tree wildlife sanctuary",
      "mountain pine ridge forest reserve",
      "benque viejo del carmen",
      "caye chapel",
      "ladyville",
      "s(ain)?t herman's blue hole",
      "rio bravo conservation",
      "spanish lookout",
      "turneffe atoll",
      "corozal bay",
      "hattieville",
      "roaring creek",
      "independence and mango creek",
      "rockstone pond",
      "la democracia",
    ],
    "whitelist": [
      "belizepics",
      "belize",
    ],
  },
  {
    "name": "imagesofbrazil",
    "search": [
      "bra(s|z)il",
      "rio de janeiro",
      "s(a|ã)o paulo",
      "salvador",
      "foz do igua(c|ç)u",
      "fortaleza",
      "curitiba",
      "natal",
      "florian(ó|o)polis",
      "manaus",
      "recife",
      "bras(í|i)lia",
      "Macei(o|ó)",
      "Arma(c|ç)(a|ã)o dos B(u|ú)zios",
      "porto seguro",
      "belo horizonte",
      "gramado",
      "Jo(a|ã)o Pessoa",
      "porto alegre",
      "Bel(e|é)m",
      "santos",
      "bonito",
      "aracaju",
      "s(a|ã)o lu(í|i)s",
      "Vit(ó|o)ria",
      "paraty",
      "ouro preto",
      "Balne(a|á)rio Cambori(u|ú)",
      "Campos do Jord(a|ã)o",
      "ilha grande",
      "pipa beach",
      "petr(ó|o)polis",
      "ilhabela",
      "ilh(é|e)us|\bsantar(e|é)m",
      "Cuiab(a|á)",
      "angra dos reis",
      "campinas",
      "ubatuba",
      "jijoca de jericoacoara",
      "po(ç|c)os de caldas",
      " cabo frio",
      "tijuca forest",
      "caldas novas\bmaragogi",
      "favela",
      "campo grande",
      "guaruj(a|á)",
      "teresina",
      "christ the redeemer",
      "sugarloaf mountain",
      "corcovado",
      "iguazu falls",
      "copacabana",
      "ipanema",
      "maracan(a|ã) stadium",
      "ibirapuera park",
      "amazon theatre",
      "teatro municipal",
      "santa teresa",
      "arpoador",
      "tijuca forest",
      "len(c|ç)ois maranhenses",
      "paulista avenue",
      "botanical garden of curitiba",
      "leblon",
      "inhotim",
      "chapada diamantina national park",
      "fort copacabana",
      "museum of the portuguese language",
      "escadaria selar(ó|o)n",
      "parque lage",
      "theatro municipal",
      "porto de galinhas",
      "sambadrome Marqu(e|ê)s de Sapuca(i|í)",
      "church of nosso senhor do bonfim",
      "meeting of waters",
      "pal(a|á)cio da alvorada",
      "cathedral of bras(í|i)lia",
      "porto da barra beach",
      "museu paulista",
      "wire opera house",
      "candel(a|á)ria church",
      "luz station",
      "maraj(ó|o)",
      "beto carrero world",
      "chapada dos veadeiros",
      "canoa quebrada",
      "basilica of the national shrine of our Lady of Aparecida",
      "hopi ha",
    ],
    'ignore': [
      "bsalvador dal(i|í)",
    ],
    "whitelist": [
      "maceio",
      "espiritosanto",
      "goiania",
      "paraiba",
      "recife",
      "maranhao",
      "campinas",
      "salvador",
      "saocarlos",
      "pelotas",
      "alagoas",
      "cuiaba",
      "jaraguadosul",
      "minasgerais",
      "carioca",
      "ilhabela",
      "portoalegre",
      "aracaju",
      "parana",
      "pernambuco",
      "roraima",
      "brasilia",
      "bahia",
      "brasilpics",
      "belempa",
      "manaus",
      "brazilpics",
      "sergipe",
      "riograndedosul",
      "portovelho",
      "piaui",
      "amazonas",
      "brasil",
      "riobranco",
      "amapa",
      "belohorizonte",
      "tocantins",
      "curitiba",
      "rondonia",
      "riodejaneiro",
      "ceara",
      "saopaulo",
      "fortaleza",
      "goias",
    ],
  },
  {
    "name": "imagesofcalifornia",
    "search": [
      "california",
      "ca",
      "californians?",
      "San Bernardino",
      "los angeles",
      "san diego",
      "san jose",
      "san francisco",
      "fresno",
      "sacramento",
      "long beach",
      "oakland",
      "bakersfield",
      "anaheim",
      "yosemite",
      "napa valley",
      "universal studios hollywood",
    ],
    'ignore': [
      "in(s|ed|ing)|driv(e|ing)|traffic|ca\.|ca glue|\bphillipines",
    ],
    "ignore_case": [
      "ca",
    ],
    "whitelist": [
      "fresnostate",
      "wikicitywalk",
      "laclippers",
      "bikela",
      "sandiegoshows",
      "westsacramento",
      "humboldt_county",
      "antelopevalley",
      "santacruzlocals",
      "sanmateocounty",
      "arcata",
      "inlandempire",
      "sfgiants",
      "prop19",
      "anaheimducks",
      "sanclemente",
      "northcounty",
      "modesto",
      "santaclarita",
      "humboldtstate",
      "sandiego",
      "simivalley",
      "sfbst",
      "sonomacounty",
      "SanJose",
      "excelsiordistrict",
      "apu",
      "fountainvalley",
      "norcalgolf",
      "menlopark",
      "socalr4r",
      "PoliticalCalifornia",
      "occ",
      "southbayla",
      "sjearthquakes",
      "49ers",
      "csuf",
      "lynwood",
      "sunnyvale",
      "coastside",
      "ssu",
      "sfv",
      "dvc",
      "slo",
      "sonoma",
      "lameetup",
      "thousandoaks",
      "caguns",
      "visalia",
      "humboldt",
      "santamaria",
      "redding",
      "napavalley",
      "ncal",
      "oakland",
      "CentralValley",
      "Bakersfield",
      "oakpark",
      "inmenlo",
      "pacificgrove",
      "grossmont",
      "burlingame",
      "losangeleskings",
      "cuestacollege",
      "pasadena",
      "westoakland",
      "islavista",
      "chicoca",
      "centralvalley",
      "norcalhiking",
      "ceanothus",
      "dirty530",
      "paloalto",
      "SantaBarbara",
      "usc",
      "biola",
      "sbcc",
      "ca4neoprogs",
      "lgcalifornia",
      "usfca",
      "asksandiego",
      "eastvale",
      "scrippscollege",
      "californiadrought",
      "venturacounty",
      "sandiegogulls",
      "foothill",
      "kernvalley",
      "sevastopol",
      "coachellavalley",
      "eastbay",
      "sandiegogonewild",
      "disneyland",
      "palmsprings",
      "dodgers",
      "sfsu",
      "scu",
      "kings",
      "sfr4r",
      "lompoc",
      "motola",
      "ridgecrest",
      "sacramento",
      "909",
      "elkgrove",
      "warriors",
      "eastla",
      "culvercity",
      "bayarea",
      "siliconvalley",
      "calireggae",
      "petaluma",
      "newportbeach",
      "mayfieldcollege",
      "calpolypomona",
      "huntingtonbeach",
      "sfbarf",
      "millbrae",
      "napa",
      "davisca",
      "novato",
      "malibu",
      "vcccd",
      "Sacramento",
      "octrees",
      "simi_valley",
      "filmindustryla",
      "ischool",
      "riversidecounty",
      "sfbayhousing",
      "coachella",
      "angelsbaseball",
      "hanford",
      "fresno",
      "sanfrancisco",
      "lajobs",
      "csudh",
      "pleasanton",
      "norcal",
      "berkeley",
      "socal",
      "flc",
      "redlands",
      "tustinca",
      "lagalaxy",
      "sfbayjobs",
      "fremont",
      "ukiah",
      "beverlyhills",
      "alameda",
      "uci",
      "pacifica",
      "conejovalley",
      "irvine",
      "harveymudd",
      "csusm",
      "disneylandresort",
      "morrobay",
      "SLO",
      "sfbsurf",
      "ucsb",
      "tree enthusiasts",
      "theclaremontcolleges",
      "lajolla",
      "taft",
      "californiabeer",
      "touro",
      "ucdavis",
      "scc",
      "lawestside",
      "csusb",
      "woodland",
      "elsegundo",
      "cca",
      "ucla",
      "weho",
      "lmu",
      "cambria",
      "sandiegooutdoors",
      "sanpedro",
      "livermore",
      "mtsanjacintocollege",
      "humboldtcounty",
      "calipornia",
      "tahoe",
      "csueb",
      "sacramentoparents",
      "scsurf",
      "sdmeetup",
      "bayareaseddit",
      "anaheim",
      "ucr",
      "santabarbara",
      "joshuatree",
      "cayucos",
      "socalhiking",
      "pepperdine",
      "pomonacollege",
      "beersandiego",
      "berkeleybooks",
      "missionbeach",
      "sfbc",
      "folsom",
      "norcalweather",
      "sierracollege",
      "csub",
      "bigbear",
      "longbeach",
      "csunorthridge",
      "AskLosAngeles",
      "losangelesrams",
      "camarillo",
      "ocparents",
      "northlaketahoe",
      "santarosa",
      "orinda",
      "slotrees",
      "lar4r",
      "mojave",
      "immovingtocalifornia",
      "sanmateo",
      "avenal",
      "silverlake",
      "mpc",
      "coachella2011",
      "riverside",
      "stanford",
      "csus",
      "westwood",
      "southerncalifornia",
      "chivasusa",
      "oaklandraiders",
      "toreros",
      "californialaw",
      "chapmanuniversity",
      "savecali",
      "ucmered",
      "sandiegojobs",
      "indio",
      "auburncalifornia",
      "palmdale",
      "santacruz",
      "Dirty530",
      "caltech",
      "gilroy",
      "babike",
      "claremont",
      "calpolitics",
      "sanjosesharks",
      "reseda",
      "stocktonca",
      "agourahills",
      "sfbayarea",
      "ucsc",
      "csulb",
      "calabasas",
      "dtla",
      "csumb",
      "laketahoe",
      "californiadisasters",
      "californiapics",
      "ucsd",
      "lakers",
      "lakerses",
      "westtoo",
      "halfmoonbay",
      "losangeles",
      "lincolnca",
      "sanjosebarracuda",
      "orangevale",
      "californiaelection",
      "southland",
      "sanmarino",
      "venice",
      "everythingsantacruz",
      "redondobeach",
      "lamesa",
      "cpslo",
      "carsonca",
      "yosemite",
      "losangelesseddit",
      "montereybay",
      "roseville",
      "highdesert",
      "waterford",
      "bakersfield",
      "csula",
      "ojai",
      "californiacannabis",
      "cityofla",
      "sdsu",
      "homfloor",
      "oaklandathletics",
      "chicostate",
      "uop",
      "lafc",
      "corona",
      "wtfcalifornia",
      "california",
      "calcommunitycolleges",
      "chulavista",
      "padres",
      "sierras",
      "calistoga",
      "ceres",
      "LosAngeles",
      "csuci",
      "sjsu",
      "santamonica",
      "vacaville",
      "orangecounty",
      "InlandEmpire",
      "chargers",
      "aisd",
      "sgv",
      "missionviejo",
      "ventura",
      "slominecraft",
      "oxnard",
      "shaverlake",
      "sanjose",
      "sanbernardino",
      "greenvilleca",
      "atascadero",
      "oxy",
      "AskSF",
      "californiaforsanders",
      "tustin",
      "orangecountyseddit",
    ],
    "wiki_blacklist": True,
  },
  {
    "name": "imagesofcanada",
    "search": [
      "canada",
      "toronto",
      "vancouver",
      "montreal",
      "quebec city",
      "ottawa",
    ],
    'ignore': [
      "WA",
    ],
    "whitelist": [
      "ottawasenators",
      "sudbury",
      "canadianforces",
      "saskatoon",
      "tfc",
      "teamcanada",
      "mississauga",
      "toronto",
      "lethbridge",
      "montrealimpact",
      "whitecapsfc",
      "saskatchewan",
      "canada",
      "guelph",
      "canadia",
      "cfl",
      "francophonie",
      "montreal",
      "pei",
      "durham",
      "ontario",
      "nunavut",
      "fundraisingcanada",
      "manitoba",
      "ocanada",
      "canadapolitics",
      "winnipegjets",
      "winnipeg",
      "whistler",
      "immigrationcanada",
      "calgaryflames",
      "kelowna",
      "regina",
      "cbc_radio",
      "stjohnsnl",
      "peterborough",
      "kitchener",
      "victoriabc",
      "calgary",
      "brampton",
      "canucks",
      "britishcolumbia",
      "barrie",
      "alberta",
      "thunderbay",
      "torontoraptors",
      "halifax",
      "nwt",
      "yukon",
      "canp41s1",
      "ottawa",
      "niagara",
      "habs",
      "torontobluejays",
      "windsorontario",
      "kingstonontario",
      "hamilton",
      "burlingtonon",
      "edmontonoilers",
      "vancouver",
      "quebec",
      "canadianpostsecondary",
      "moncton",
      "leafs",
      "fredericton",
      "newfoundland",
      "newbrunswickcanada",
      "waterloo",
      "novascotia",
      "edmonton",
      "londonontario",
    ],
  },
  {
    "name": "imagesofchile",
    "search": [
      "chile",
      "santiago",
      "torres del paine",
      "valpara(i|í)so",
      "punta arenas",
      "san pedro de atacama",
      "puerto montt",
      "iquique",
      "arica",
      "chilo(é|e) island",
      "Vi(n|ñ)a del Mar",
      "Puc(o|ó)n",
      "puerto varas",
      "puetro natales",
      "antofagasta",
      "la serena",
      "concepci(o|ó)n",
      "temuco",
      "osorno",
      "chill(a|á)n",
      "coyhaique",
      "calama",
      "villarrica",
      "robinson crusoe island",
      "frutillar",
      "los andes",
      "lauca national park",
      "copiap(ó|o)",
      "rancagua",
      "(lake san rafael|san rafael lake)",
      "caldera",
      "la campana",
      "talca",
      "Conguill(í|i)o",
      "pichilemu",
      "algarrobo",
      "puerto williams",
      "puerto chacabuco",
      "santa cruz",
      "providencia",
      "san felipe",
      "panguipulli\bolmu(e|é)\b|valle nevado",
      "ancud",
      "huilo-huilo",
      "Curic(ó|o)",
      "chile chico",
      "torres del paine",
      "san Crist(o|ó)bal",
      "lauca national park",
      "valle de la luna",
      "santiago metropolitan park",
      "la moneda palace",
      "plaza de armas",
      "Los Pingüinos",
      "magdalena island",
      "museo chileno de arte precolombino",
      "san rafael glacier",
      "santa Luc(i|í)a",
      "Caj(o|ó)n del Maipo|\bmuseum of memory and human rights",
      "valle nevado",
      "chilean national museum of fine arts",
      "villarrica",
      "cordillera paine",
      "parque forestal",
      "costanera center",
      "osomo",
      "humberstone and santa laura saltpeper works",
      "Chungar(a|á)",
      "ttodos los santos",
      "el morado",
      "fantasilandia",
      "san rafael lake",
      "centro cultural palacio de la moneda",
      "ojos del salado",
      "pumalin park",
      "Conguill(i|í)o national park",
      "villarrica lake",
      "chilean national zoo",
      "bosque de fray jorge national park",
      "beagle channel",
      "casa colorada",
      "Pukar(a|á) de quitor",
      "Re(n|ñ)aca beach",
      "calbuco",
      "Estaci(o|ó)n Mapocho",
      "tronador",
      "grey glacier",
      "lake Peho(e|é)",
      "puyehue lake",
      "ojos del caburgua",
      "Puntiagudo-Cord(o|ó)n Cenizos",
      "church of san pedro de atacama",
      "Fitz Roy",
      "chalt(e|é)n",
      "andes",
      "easter island",
      "w(e|é)on",
      "cerro castillo",
      "carlos ib(a|á)(ñ|n)ez",
      "la paz",
      "dynevor",
      "mapuche",
      "chilla",
      "la silla",
      "atacama",
      "el potre chico",
    ],
    'ignore': [
      "california",
    ],
    "ignore_case": [
      "chile",
    ],
    "whitelist": [
      "santiago",
      "chilents",
      "chilecringe",
      "topmusicchile",
      "chilecirclejerk",
      "laroja",
    ],
    "blacklist": [
      "{'caldera', 'supremeclothing', 'foodporn', 'food'}",
    ],
  },
  {
    "name": "imagesofchina",
    "search": [
      "china",
      "beijing",
      "shanghai",
      "guangzhou",
      "xi'an",
      "shenzhen",
    ],
    'ignore': [
      "(from|made in) china",
    ],
    "whitelist": [
      "nanjing",
      "wuhan",
      "shanghai",
      "dalian",
      "china",
      "hongkong",
      "chengdu",
      "guangzhou",
      "beijing",
      "chinaart",
      "taiwan",
      "chinapics",
      "harbin_china",
      "travelchina",
      "chinesereddit",
      "macau",
      "shenzhen",
    ],
    "wiki_blacklist": True,
  },
  {
    "name": "imagesofcolorado",
    "search": [
      "colorado",
      "co",
      "coloradans?",
      "rocky mountain national park",
      "estes park",
      "pikes peak",
      "garden of the gods",
      "cheyenne mountain zoo",
      "mesa verde national park",
      "denver",
      "colorado\bsprings",
      "aurora\b(co|colorado)",
      "fo?r?t\bcollins",
      "lakewood",
      "thornton",
      "pueblo",
      "arvada",
      "westminster",
      "centennial\b(colorado|co)",
    ],
    'ignore': [
      "-|aurora borealis|co.?worker|co\.|\/co\/|\bthornton state",
    ],
    "ignore_case": [
      "Co",
    ],
    "whitelist": [
      "denverpics",
      "denveru",
      "durango",
      "cuboulder",
      "greeley",
      "beavercreek",
      "cohiphop",
      "pueblo",
      "colorado",
      "cudenver",
      "msdc",
      "castlerock",
      "comines",
      "uccs",
      "switchbacksfc",
      "unco",
      "denvergardener",
      "twn",
      "cobeer",
      "cortez",
      "breckenridge",
      "cofishing",
      "coloradoschoolofmines",
      "denverfood",
      "fortcollins",
      "coloradooffroad",
      "cosnow",
      "denverlist",
      "grandjunction",
      "pbville",
      "c710lorado",
      "coguns",
      "auroraco",
      "coloradojobs",
      "cobike",
      "denvervolunteers",
      "coclimbing",
      "cotreegifting",
      "coloradohikers",
      "littlebigdenver",
      "centennialdtc",
      "erieco",
      "denvercutthroats/",
      "vail",
      "gunnison",
      "fourcorners",
      "denvermotorcycles",
      "couplesofcos",
      "denver",
      "rapids",
      "denverbroncos",
      "denvermusic",
      "roaringfork",
      "denverjobs",
      "longmont",
      "denvergaymers",
      "coloradosprings",
      "denvercomiccon",
      "cowx",
      "fruita",
      "vacationcolorado",
      "fortlewiscollege",
      "rrcc",
      "csufoco",
      "auraria_campus",
      "boulderuncut",
      "littleton",
      "denvernuggets",
      "denversoccer",
      "coloradoavalanche",
      "coloradosports",
      "coloradocollege",
      "coents",
      "loveland",
      "goldenco",
      "coloradoscene",
      "steamboat/",
      "denvercirclejerk",
      "summit",
      "coloradorockies",
      "boulder",
    ],
    "blacklist": [
      "{'london', 'panthers', 'trees'}",
    ],
  },
  {
    "name": "imagesofconnecticut",
    "search": [
      "connecticut",
      "ct",
      "connecticuters?",
      "mystic seaport",
      "lake compounce",
      "gillette castle state park",
      "mark twain house",
      "mystic aquarium and institute",
      "bridgeport",
      "new\bhaven",
      "hartford",
      "stamford",
      "waterbury",
      "norwalk",
      "danbury",
      "new\bbritain",
    ],
    'ignore': [
      "ct.(scan|machine|unit|precisa)",
    ],
    "ignore_case": [
      "Ct",
    ],
    "whitelist": [
      "easternct",
      "sono",
      "tolland",
      "enfieldct",
      "oldsaybrook",
      "subaru_ct",
      "waterburyct",
      "hartford",
      "connecticutr4r",
      "movingtoct",
      "connecticut",
      "ctjobs",
      "stamfordct",
      "norwalk",
      "connecticutkayakers",
      "uconn",
      "newhaven",
      "milford",
      "wcsu",
      "ctbeer",
      "woodburyct",
    ],
  },
  {
    "name": "imagesofdelaware",
    "search": [
      "delaware",
      "delwarans?",
      "wilmington",
      "hagley museum",
      "nemours mansion",
      "cape henlopen",
      "dover",
      "newark\b(de|delaware)",
      "bear\b\b(delaware|de)",
      "middletown",
      "brookside",
      "Glasgow\b(de|delaware)",
      "Hockessin",
      "pike\bcreek\bvalley",
      "Smyrna",
    ],
    'ignore': [
      "new jersey",
    ],
    "whitelist": [
      "delawareamiibo",
      "delaware4sanders",
      "fireflyfestival",
      "hirede",
      "asylum13",
      "deguns",
      "delaware",
      "wilmingtonde",
      "delawarent",
      "delmoto",
      "netde",
      "motde",
      "newarkde",
      "udel",
      "bikede",
      "hopheadsde",
      "slowerlower",
      "delawarepolitics",
    ],
    "blacklist": [
      "{'easternshoremd'}",
    ],
  },
  {
    "name": "imagesofengland",
    "search": [
      "england",
      "london",
      "oxford",
      "manchester",
      "new castle upon tyne",
      "birmingham",
      "york",
      "cambridge",
      "windsor",
      "canterbury",
      "brighton",
      "bristol",
      "leeds",
      "new forest",
      "straford-upon-avon",
      "nottingham",
      "bournemouth",
      "greenwich",
      "portsmouth",
      "peak district",
      "sheffield",
      "warwick",
      "exeter",
      "salisbury",
      "yorkshire dales",
      "newquay",
      "greater manchester",
      "lake district national park",
      "leicester",
      "windermere",
      "keswick",
      "harrogate",
      "winchester",
      "cheltenham",
      "peterborough",
      "southport",
      "penrith",
      "glastonbury",
      "ashford",
      "milton keynes",
      "coventry",
      "colchester",
    ],
    'ignore': [
      "new england",
    ],
    "ignore_case": [
      "ON",
    ],
    "whitelist": [
      "englandpics",
      "england",
    ],
    "blacklist": [
      "{'gunporn', 'ockytop', 'guns', 'nascar', 'newzealand', 'boston', 'hunting', 'australia', 'supremeclothing', 'birmingham', 'londonontario', 'fo4'}",
    ],
  },
  {
    "name": "imagesofflorida",
    "search": [
      "florida",
      "fl",
      "Floridians?",
      "jacksonville",
      "miami",
      "tampa",
      "Saint\bPetersburg",
      "orlando",
      "Hialeah",
      "Tallahassee",
      "Fo?r?t\bLauderdale",
      "Port\bSaint\bLucie",
      "Pembroke\bPines",
    ],
    'ignore': [
      "fl studios?",
    ],
    "whitelist": [
      "orlando",
      "naples_fl",
      "bocaraton",
      "tampa",
      "floridaman",
      "daytonabeach",
      "jaxbeer",
      "wtf_florida",
      "daytonastate",
      "southflorida",
      "panamacity",
      "miabeer",
      "soflabeer",
      "swfl",
      "nwfl",
      "floridabrew",
      "portstlucie",
      "flaglercollege",
      "flvs",
      "stpetersburgfl",
      "floridapoly",
      "miami",
      "unf",
      "florida",
      "staugustine",
      "umiami",
      "pensacola",
      "sarasota",
      "tlh",
      "ucfknights",
      "onthewaterfront",
      "ucf",
      "riverviewfl",
      "fsu",
      "lakeland",
      "tampabaybeer",
      "jacksonville",
      "palmcoast",
      "keyshappenings",
      "miamihurricanes",
      "floridagators",
      "fortlauderdale",
      "ufl",
      "orlandodisneyarea",
      "321",
      "usf",
      "centralflorida",
      "treasurecoast",
      "tallahassee",
      "gnv",
      "northlakecounty",
    ],
    "blacklist": [
      "{'edmproduction', 'mechanicalkeyboards', 'edmprodcirclejerk'}",
    ],
  },
  {
    "name": "imagesoffrance",
    "search": [
      "france",
      "paris",
      "marseille",
      "cannes",
      "strasbourg",
      "toulouse",
      "eiffel tower",
      "louvre",
      "french riviera",
      "arc de triomphe",
      "versailles",
      "Musée d'Orsay",
      "Sacré-C(oe|œ)ur",
      "jardin du luxembourg",
    ],
    'ignore': [
      "paris (tx|texas|island|hilton|dylan|abra)",
    ],
    "whitelist": [
      "montpellier",
      "toulouse",
      "strasbourg",
      "tours",
      "grenoble",
      "bordeaux",
      "lyon",
      "reunionisland",
      "aixmarseille",
      "lille",
      "nantes",
      "france",
      "clermontfd",
      "bretagne",
      "acadie",
      "grandsud",
      "normandie",
      "bourgogne",
      "paris",
      "francepics",
    ],
  },
  {
    "name": "imagesofgeorgia",
    "search": [
      "georgia",
      "ga",
      "Georgians?",
      "atlanta",
      "columbus\b(georgia|ga)",
      "Savannah",
      "athens\b(ga|georgia)",
      "sandy\bsprings",
      "macon",
      "roswell\b(ga|georgia)",
      "albany\b(ga|georgia)",
      "johns\bcreek",
      "warner\brobins",
    ],
    'ignore': [
      "georgia graham",
    ],
    "ignore_case": [
      "ga",
    ],
    "whitelist": [
      "smyrna",
      "marietta",
      "eastpoint",
      "valdosta",
      "gwinnett",
      "dahlonega",
      "BrunswickGA",
      "romega",
      "savannah",
      "franklincountyga",
      "macon",
      "lagrange",
      "CarrolltonGeorgia",
      "waycross",
      "JasperGA",
      "stsimonsisland",
      "middlegeorgia",
      "columbiacounty",
      "forsyth",
      "sandysprings",
      "ludowici",
      "roswell",
      "JekyllIsland",
      "mableton",
      "AlbanyGA",
      "dacula",
      "FayCo",
      "flowerybranch",
      "paulding",
      "midtownatlanta",
      "mariettaga",
      "columbusga",
      "statesboro",
      "cherokeecountyga",
      "augusta",
      "newnan",
      "leesburgga",
      "dvillega",
      "daltonga",
      "atlanta",
      "alpharetta",
      "SummervilleGA",
      "Dunwoody",
      "decaturga",
      "georgia",
      "johnscreek",
      "HinesvilleGA",
      "dublinga",
      "kennesaw",
      "BarrowCounty",
      "acworth",
      "cartersville",
      "woodstockga",
      "PeachtreeCity",
      "HenryCounty",
      "snobbery",
      "conyers",
      "athens",
      "lilburn",
    ],
  },
  {
    "name": "imagesofguatemala",
    "search": [
      "guatemala",
      "tikal",
      "Lake Atitl(á|a)n",
      "pacaya",
      "dulce river",
      "lake Pet(é|e)n Itz(á|a)|\bpet(é|e)n department",
      "panajachel",
      "cobán",
    ],
    "whitelist": [
      "guatemala",
      "guatemalapics",
    ],
  },
  {
    "name": "imagesofhawaii",
    "search": [
      "hawaii",
      "Hawaiians?",
      "Honolulu",
      "pearly\bcity",
      "hilo",
      "kailua",
      "Waipahu",
      "Kaneohe",
      "Mililani\bTown",
      "Kahului",
      "Ewa\bGentry",
      "warner\brobins\b|kihei",
    ],
    'ignore': [
      "hawaiian rolls?",
    ],
    "whitelist": [
      "hawaiifit",
      "hawaii",
      "hawaiipics",
      "himusic",
      "bicyclehawaii",
      "hawaiijobs",
      "honolulu",
      "universityofhawaii",
      "oahu",
      "kauai",
      "hawaiigardening",
      "maui",
      "bigisland",
    ],
  },
  {
    "name": "imagesofhongkong",
    "search": [
      "hong kong",
      "victoria peak",
      "lantao island",
      "Ngong Ping",
      "Po Lin Monastery",
      "lamma island",
      "cheung chao",
    ],
    "whitelist": [
      "hongkong",
      "hongkongpics",
    ],
  },
  {
    "name": "imagesoficeland",
    "search": [
      "iceland",
    ],
    "whitelist": [
      "iceland",
      "island",
      "klakinn",
    ],
  },
  {
    "name": "imagesofidaho",
    "search": [
      "idaho",
      "Idahoans?",
      "boise",
      "nampa",
      "Meridian",
      "Idaho\bFalls",
      "Pocatello",
      "Caldwell",
      "Coeur\bd'Alene",
      "Twin\bFalls",
      "lewiston",
    ],
    'ignore': [
      "idaho springs",
    ],
    "whitelist": [
      "idaho",
      "courdalene",
      "idahodogcommunity",
      "mountainhome",
      "pocatello",
      "boise",
      "twinfalls",
    ],
  },
  {
    "name": "imagesofillinois",
    "search": [
      "illinois",
      "Illinoisans?",
      "IL",
      "chicago",
      "Aurora\b(IL|Illinois)",
      "rockford",
      "Joliet",
      "naperville",
      "springfield",
      "peopria",
      "elgin\b(IL|illinois)",
      "Waukegan",
    ],
    'ignore': [
      "il",
    ],
    "whitelist": [
      "hawks",
      "chicubs",
      "chicagogaming",
      "whitesox",
      "lasallecounty",
      "chibears",
      "grayslakeillinois",
      "salukis",
      "southernillinois",
      "chicago",
      "illinois",
      "centralillinois",
      "rockford",
      "chicagobulls",
    ],
    "blacklist": [
      "{'thesimpsons', 'guns'}",
    ],
  },
  {
    "name": "imagesofindia",
    "search": [
      "indian?",
      "bharat",
      "hindustan",
      "bharatiya",
      "hindu",
      "goa",
      "mumbai",
      "new delhi",
      "bengaluru",
      "chennai",
      "jaipur",
      "hyderabad",
      "agra",
      "kolkata",
      "pondicherry",
      "ooty",
      "shimla",
      "darjeeling",
      "kochi",
      "munnar",
      "udaipur",
      "mysore",
      "manali",
      "manali",
      "himachal pradesh",
      "pune",
      "varanasi",
      "kodaikanal|\bleh",
      "thiruvananthapuram",
      "nainital",
      "ahmedabad",
      "gangtok",
      "chandigarh",
      "amritsar",
      "srinagar",
      "jodhpur",
      "jaisalmer",
      "madurai",
      "kanyakumari",
      "coimbatore",
      "visakhapatnam",
      "rishikesh",
      "alappuzha",
      "mangalore",
      "mahabaleshwar",
      "dharamsala",
      "haridwar",
      "mussoori",
      "kovalam",
      "shillong",
      "indore",
      "(mount|mt)\babu",
      "dehradun",
      "p(or)?t blair",
      "andhra pradesh",
      "bihar",
      "chhattisgarh",
      "goa",
      "gujarat",
      "haryana",
      "himachal pradesh",
      "jammu and kashmir",
      "jharkhand",
      "karnataka",
      "kerala",
      "madhya pradesh",
      "maharashtra",
      "odisha",
      "punjab",
      "arunachal pradesh",
      "assam",
      "manipur",
      "meghalaya",
      "mizoram",
      "nagaland",
      "sikkim",
      "tripura",
      "rajasthan",
      "tamil nadu",
      "telangana",
      "uttar pradesh",
      "uttarakhand",
      "west bengal",
      "adaman islands?",
      "nicobar islands?",
      "chandigarh",
      "dadra haveli",
      "nagar haveli",
      "daman and diu",
      "lakshadweep",
      "delhi",
      "puducherry",
      "pondicherry",
      "uttaranchal",
      "arunachal",
      "andhra",
      "madhya bharat",
      "orissa",
    ],
    'ignore': [
      "goa crew",
    ],
    "whitelist": [
      "varanasi",
      "noida",
      "marathi",
      "nagpur",
      "jabalpur",
      "navimumbai",
      "indianstandupcomedy",
      "mfaindia",
      "bhopal",
      "satara",
      "jharkhand",
      "udaipur",
      "rajkot",
      "leh",
      "coimbatore",
      "indianfitness",
      "sitar",
      "nri",
      "sangli",
      "asansol",
      "uttarakhand",
      "chennai",
      "tamil",
      "chhattisgarh",
      "icm",
      "sanskrit",
      "bareilly",
      "pondicherry",
      "himachalpradesh",
      "northeastindia",
      "indianhistory",
      "indiangaming",
      "gurgaon",
      "indianpics",
      "jalandhar",
      "indianbooks",
      "aurangabad",
      "dehradun",
      "kolkata",
      "tamilnadu",
      "ecigindia",
      "desiads",
      "lonavala",
      "abcdesis",
      "kannada",
      "angrezinewspapers",
      "hyderabad",
      "wtfindia",
      "indiainvestments",
      "jodhpur",
      "indianpeoplegifs",
      "shimla",
      "indiansports",
      "royalenfield",
      "desicringe",
      "bollywoodtrailers",
      "indianstartups",
      "antrixcorporation",
      "ranchi",
      "kashmir",
      "punjabi",
      "telugu",
      "bombay",
      "indianfood",
      "lakshadweep",
      "atheismindia",
      "manipur",
      "bhilai",
      "punjab",
      "classicalindian",
      "dombivli",
      "ipl",
      "rajasthan",
      "lgbtindia",
      "sikkim",
      "bhubaneswar",
      "gwalior",
      "imphal",
      "urdu",
      "assam",
      "ghaziabad",
      "pali",
      "kochi",
      "notthepyaaz",
      "kalyan",
      "indianfootball",
      "ghatisongs",
      "anand",
      "karnataka",
      "andamannicobarislands",
      "indiamain",
      "uttarpradesh",
      "jamshedpur",
      "ahmedabad",
      "nmmusicindia",
      "isro",
      "askindia",
      "delhi",
      "sahitya",
      "nashik",
      "andhrapradesh",
      "ajmer",
      "aligarh",
      "westbengal",
      "indianautos",
      "indiancomicbooks",
      "bengaluru",
      "southasia",
      "indianbands",
      "lucknow",
      "jaipur",
      "indiareads",
      "desishowerthoughts",
      "indianfoodporn",
      "mizoram",
      "indiandefense",
      "kanpur",
      "hindi",
      "inindiannews",
      "indore",
      "odisha",
      "haryana",
      "goa",
      "kollywood",
      "indianrightwing",
      "indianwriters",
      "guwahati",
      "nagaland",
      "allahabad",
      "kozhikode",
      "desigifs",
      "mohali",
      "ludhiana",
      "kerala",
      "aizawl",
      "trivandrum",
      "gandhinagar",
      "india",
      "agra",
      "indiapolicy",
      "ipm",
      "madras",
      "indiancoins",
      "mpoi",
      "bangalore",
      "nainital",
      "incredibleindia",
      "southasianhistory",
      "bollywood",
      "bharuch",
      "tilinindia",
      "vadodara",
      "kolhapur",
      "trollywood",
      "dealsforindia",
      "indianews",
      "oldindia",
      "mathura",
      "dharamsala",
      "vijaywada",
      "bengalilanguage",
      "desifoodies",
      "mumbai",
      "desiweddings",
      "jammu",
      "faridabad",
      "maharashtra",
      "republicofindia",
      "southasianart",
      "indianpolitics",
      "newdelhi",
      "indianindie",
      "vasai",
      "bharat",
      "desihumor",
      "indianmythology",
      "pune",
      "gujarat",
      "indiansuperleague",
      "amritsar",
      "meerut",
      "almora",
      "indiancinema",
      "indianleft",
      "arunachal",
      "jammukashmir",
      "bihar",
      "srinagar",
      "telangana",
      "indianents",
      "raipur",
      "bestofindia",
      "indianblogrecipes",
      "durgapur",
      "madhyapradesh",
      "darjeeling",
      "chandigarh",
      "travelsinindia",
    ],
    "wiki_blacklist": True,
  },
  {
    "name": "imagesofindiana",
    "search": [
      "indiana",
      "Indianians?",
      "hoosiers?",
      "Indianapolis",
      "F(or)?t\bWayne",
      "evansville",
      "south\bbend",
      "hammond",
      "bloomington",
      "gary\bindiana",
      "carmel\bindiana",
      "fishers\bindiana",
      "muncie",
    ],
    'ignore': [
      "indiana (jon|jones|evans)",
    ],
    "whitelist": [
      "indiana",
    ],
    "blacklist": [
      "{'topgear', 'jurassicworldapp'}",
    ],
  },
  {
    "name": "imagesofiowa",
    "search": [
      "iowa",
      "Iowans?",
      "des moines",
      "cedar rapids",
      "davenport",
      "sioux city",
      "waterloo (IA|iowa)",
      "council bluffs",
      "ames",
      "Dubuque",
    ],
    'ignore': [
      "(kennedy|adam) davenport",
    ],
    "whitelist": [
      "ankeny",
      "grinnell",
      "clarkeu",
      "cornellcollege",
      "masoncity",
      "siouxcity",
      "councilbluffs",
      "uni",
      "iastate",
      "iowajobs",
      "dubuque",
      "cedarrapids",
      "iowagamers",
      "decorah",
      "waterlooiowa",
      "quadcity",
      "okoboji",
      "uiowa",
      "iowa",
      "ames",
      "iowabeer",
      "iowacity",
      "desmoines",
    ],
    "blacklist": [
      "{'sandersforpresident', 'mycology', 'toronto', 'whatisthisthing', 'whatisthisplant', 'whatsthisplant'}",
    ],
  },
  {
    "name": "imagesofiran",
    "search": [
      "iran",
      "tehran",
      "mashhad",
      "shiraz",
      "isfahan",
      "tabriz",
      "yazd",
      "qeshm",
      "kashan",
    ],
    "whitelist": [
      "iranianmusic",
      "iranpics",
      "iranpolitics",
      "iranlgbt",
      "iran",
      "teammelli",
    ],
  },
  {
    "name": "imagesofisleofman",
    "search": [
      "isle of man",
      "castle rushen",
      "peel castle",
      "calf of man",
      "leece museum",
      "snaefell",
      "langness peninsula",
      "peel cathedral",
      "south barrule|\bmaughold head",
      "bradda hill",
      "north barrule",
      "chicken rock",
      "mull hill",
      "spanish head",
      "castletown",
      "porn erin",
      "ramsey",
    ],
    'ignore': [
      "(aaron|david|gordon|jalen|hms|laura|steve|geoff|the|mega|kelly|jonbenet).ramsey",
    ],
    "whitelist": [
      "isleofmanphotos",
      "isleofman",
    ],
    "blacklist": [
      "{'shitgunnerssay', 'tennesseetitans', 'fantasypl', 'gameofthrones', 'hbogameofthrones', 'ck2gameofthrones', 'soccer', 'gunners'}",
    ],
  },
  {
    "name": "imagesofjapan",
    "search": [
      "japan",
      "tokyo",
      "kyoto",
      "m(oun)?t\bfuji",
      "meiji shrine",
      "kinkaku-ji",
      "kiyomizu-dera",
      "senso-ji",
      "osaka",
      "nagoya",
      "hakone",
    ],
    'ignore': [
      "tokyo (ghoul|mew)",
    ],
    "whitelist": [
      "japan",
      "fukuoka",
      "japanart",
      "rideitjapan",
      "japanpics",
      "japanesefiction",
      "osaka",
      "hiroshima",
      "nagoya",
      "japanesemusic",
      "npb",
      "japantravel",
      "japanplaces",
      "japanesefood",
      "japanlife",
      "otaku",
      "fukushimachronicles",
      "jleague",
      "normaldayinjapan",
      "japanparents",
      "kansai",
      "japansports",
      "okinawa",
      "kyoto",
      "japannews",
      "jpop",
      "tokyo",
    ],
  },
  {
    "name": "imagesofkansas",
    "search": [
      "kansas",
    ],
    "whitelist": [
      "lawrence",
      "universityofkansas",
      "topeka",
      "hutchinson",
      "atchison",
      "wichita",
      "southwestkansas",
      "salina",
      "littleapple",
      "kansas",
      "kstate",
      "pittstate",
      "washburn",
      "kansascity",
      "overlandpark",
      "ksguns",
      "emporia",
    ],
  },
  {
    "name": "imagesofkentucky",
    "search": [
      "kentucky",
    ],
    "whitelist": [
      "louisville",
      "covington",
      "nku",
      "wku",
      "mountvernonkentucky",
      "murray",
      "paducah",
      "winchesterky",
      "universityofkentucky",
      "moreheadstate",
      "bowlinggreen",
      "morehead",
      "bardstown",
      "pikeville",
      "kentucky",
      "danvilleky",
      "frankfort",
      "lexington",
      "allhail",
      "newportky",
      "eku",
      "owensboro",
      "ashlandkentucky",
    ],
  },
  {
    "name": "imagesoflibya",
    "search": [
      "libyan?",
      "tripoli",
      "leptis magna",
      "benghazi",
      "tobruk",
      "ghadames",
      "shahhat",
      "sabha",
      "sabratha",
      "zuwarah",
      "gharyan",
      "khoms",
      "ghat",
      "al ayda",
      "sirte",
      "misurata",
      "zawiya",
      "bani walid",
      "zintan",
      "janzur",
      "darnah",
      "zliten",
      "marj",
      "ajdabiya",
      "sirte district",
      "nalut",
      " ra's lanuf",
      "murzuq district\b|byafran",
      "awjila",
      "sorman",
      "al jawf",
    ],
    "whitelist": [
      "libya",
      "libyanconflict",
    ],
  },
  {
    "name": "imagesoflouisiana",
    "search": [
      "louisiana",
    ],
    "whitelist": [
      "jeffersonparish",
      "lsu",
      "louisianatech",
      "cajunmusic",
      "cajunhistory",
      "lakecharles",
      "nsula",
      "ascensionparish",
      "louisiana",
      "laworks",
      "uno",
      "houma",
      "ull",
      "centrallouisiana",
      "neworleans",
      "bellechasse",
      "lsufootball",
      "batonrouge",
      "louisianajobs",
      "nsu",
      "acadiana",
      "plaqueminesparish",
      "shreveport",
      "hammond",
      "ponchatoula",
      "ulmonroe",
    ],
  },
  {
    "name": "imagesofmaine",
    "search": [
      "maine",
    ],
    'ignore': [
      "maine coon",
    ],
    "whitelist": [
      "mainebeer",
      "portlandme",
      "mainehistory",
      "maine",
      "skimaine",
      "mainefood",
    ],
  },
  {
    "name": "imagesofmaldives",
    "search": [
      "maldives",
      "maldivian",
      "Malé",
      "Hulhumal(é|e)",
      "mulee-aage",
      "hulhul(é|e)",
      "hithadhoo",
      "villingili",
      "maradhoo",
      "hulhumeedhoo",
      "thilafushi",
      "thilafushi",
      "meedhoo",
    ],
    "whitelist": [
      "maldives",
    ],
  },
  {
    "name": "imagesofmaryland",
    "search": [
      "maryland",
    ],
    "whitelist": [
      "maryland",
    ],
  },
  {
    "name": "imagesofmassachusetts",
    "search": [
      "massachusetts",
    ],
    "whitelist": [
      "massachusetts",
    ],
  },
  {
    "name": "imagesofmexico",
    "search": [
      "mexico",
      "tulum",
      "chichen itza",
      "museo nacional de antropolog(í|i)a",
      "chapultepec castle",
      "coba",
      "Canc(ú|u)n",
      "playa del carmen",
      "cabo san lucas",
      "puerto vallarta",
    ],
    'ignore': [
      "new mexico",
    ],
    "whitelist": [
      "fotosmexico",
      "mexico",
    ],
  },
  {
    "name": "imagesofmichigan",
    "search": [
      "michigan",
    ],
    'ignore': [
      "michigan city",
    ],
    "whitelist": [
      "michigan",
    ],
  },
  {
    "name": "imagesofminnesota",
    "search": [
      "minnesota",
    ],
    "whitelist": [
      "minnesota",
    ],
  },
  {
    "name": "imagesofmississippi",
    "search": [
      "mississippi",
    ],
    'ignore': [
      "mississippi river",
    ],
    "whitelist": [
      "mississippi",
    ],
  },
  {
    "name": "imagesofmissouri",
    "search": [
      "missouri",
    ],
    "whitelist": [
      "missouri",
    ],
  },
  {
    "name": "imagesofmontana",
    "search": [
      "montana",
      "MT",
      "glacier national park",
      "bozeman",
      "whitefish",
      "great falls",
      "missoula",
      "west yellowstone",
      "kalispell",
      "helena",
      "big sky",
      "little bighorn battlefield",
      "gardiner",
      "livingston",
      "flathead lake",
      "west glacier",
      "butte",
      "red lodge",
      "virginia city",
      "havre",
      "polson",
      "columbia falls",
      "giant springs state park",
      "anaconda",
      "miles city",
      "glendive",
      "lewistown",
      "cooke city",
      "silver gate",
      "thompson falls",
      "bigfork",
      "lake mcdonald",
      "wild horse island",
      "east glacier park",
      "fort benton",
      "three forks",
      "grinnell glacier",
      "logan pass",
      "hungry horse",
      "monarch",
      "gallatin gateway",
      "deer lodge",
      "dillon",
      "forsyth",
      "hardin",
      "cut bank",
      "hot springs",
      "big timber",
    ],
    'ignore': [
      "(hannah|joe|tony) montana",
    ],
    "ignore_case": [
      "Mt",
    ],
    "whitelist": [
      "montana",
    ],
    "blacklist": [
      "{'elitedangerous', 'washingtondc', 'nova', 'yugioh', 'arkansas', 'sneks', 'silverbugs', 'flytying'}",
    ],
  },
  {
    "name": "imagesofnebraska",
    "search": [
      "nebraska",
    ],
    "whitelist": [
      "nebraska",
    ],
  },
  {
    "name": "imagesofnetherlands",
    "search": [
      "netherlands",
      "amsterdam",
      "rotterdam",
      "hague",
      "maastricht",
      "utrecht",
      "rijksmuseum",
      "anne frank house",
      "keukenhof",
      "vondelpark",
      "madurodam",
    ],
    'ignore': [
      "new york",
    ],
    "whitelist": [
      "netherlandspics",
      "netherlands",
      "thenetherlands",
    ],
  },
  {
    "name": "imagesofnevada",
    "search": [
      "nevada",
    ],
    'ignore': [
      "nevada city",
    ],
    "whitelist": [
      "nevada",
      "burningman",
    ],
  },
  {
    "name": "imagesofnewhampshire",
    "search": [
      "new hampshire",
    ],
    "whitelist": [
      "newhampshire",
    ],
  },
  {
    "name": "imagesofnewjersey",
    "search": [
      "new jersey",
    ],
    "ignore_case": [
      "new jersey",
    ],
    "whitelist": [
      "newjersey",
    ],
  },
  {
    "name": "imagesofnewmexico",
    "search": [
      "new mexico",
      "santa fe",
      "albuquerque",
      "roswell",
      "taos",
      "carlsbad",
      "ruidoso",
      "las cruces",
      "white sands",
      "los alamos",
      "alamogordo",
      "carlsbad",
      "chaco culture",
      "tucumcari",
      "bandelier",
      "silver city",
      "red river",
      "farmington",
      "santa rosa",
      "deming",
      "acoma pueblo",
      "lordsburg",
      "angel fire",
      "clayton",
      "Truth or consequences",
      "Espa(n|ñ)ola",
      "zuni",
      "clovis",
      "mesilla",
      "artesia",
      "socorro",
      "eagle nest lake",
      "portales",
      "Abiqui(ú|u)",
      "shiprock",
      "taos pueblo",
      "taos ski valley",
      "city of rocks",
      "chama",
      "elephant butte",
    ],
    'ignore': [
      "minnesota",
    ],
    "ignore_case": [
      "chama",
    ],
    "whitelist": [
      "carlsbadnm",
      "santafe",
      "newmexico",
      "nmsu",
      "albuquerque",
      "unm",
      "lascruces",
    ],
    "blacklist": [
      "{'atlanta'}",
    ],
  },
  {
    "name": "imagesofnewyork",
    "search": [
      "new york",
      "NYC?",
      "long island",
      "albany",
      "thousand islands",
      "finger lakes",
      "rochester",
      "syracuse",
      "lake placid",
      "ithaca",
      "lake george",
      "binghampton",
      "montauk",
      "plattsburgh",
      "woodstock",
      "poughkeepsie",
      "woodbury",
      "new paltz",
      "bethel",
      "saratoga springs",
      "watkins glen",
      "alexandria bay",
      "west point",
      "sleepy hollow",
      "elmira",
      "rhinebeck",
      "tarrytown",
      "cooperstown",
      "ellicottville",
      "fire island",
      "cold spring",
      "bear (mountain|mt)",
      "utica",
      "corning",
      "white plains",
      "p(or)?t chester",
      "shelter island",
      "cayuga lake",
      "letchworth state park",
      "hyde park",
      "watertown",
      "amityville",
      "westbury",
      "margaret lewis norrie state park",
      "ogdensburg",
      "port jefferson",
    ],
    'ignore': [
      "austin",
    ],
    "ignore_case": [
      "(Ny|ny|nY)",
    ],
    "whitelist": [
      "nyc",
      "nychistory",
      "newyork",
      "nycstreetart",
      "nycpics",
    ],
    "blacklist": [
      "{'austin'}",
    ],
  },
  {
    "name": "imagesofnewzealand",
    "search": [
      "new zealand",
      "auckland",
      "queenstown",
      "christchurch",
      "wellington",
      "rotorua",
      "dunedin",
      "taupo",
      "nelson",
      "napier",
      "hawke's bay",
      "wanaka",
      "bay of islands",
      "marlborough",
      "lake tekapo",
      "kaikoura",
      "picton",
      "te anau",
      "blenheim",
      "fox glacier",
      "paihai",
      "tauranga",
      "coromandel",
      "coromandel",
      "akaroa",
      "abel tasman",
      "greymouth",
      "hanmer springs",
      "grisborne",
      "cape reinga",
      "waitomo",
      "invercargill",
      "new plymouth",
      "palmerston north",
      "lake wanaka",
      "timaru",
      "whanganui",
      "thames",
      "ashburton",
      "stewart island",
      "hokitika",
      "oamaru",
      "matamata",
      "warkworth",
      "arrowtown",
      "cromwell",
      "wakatipu",
      "westport",
      "milford sound",
      "sky tower",
      "lake taupo",
      "bay of islands",
      "lake wanaka",
      "tongariro",
      "Fiordland\bwaiotapu",
      "huka falls",
      "abel tasman",
      "waitomo",
      "doubtful sound",
      "Toit(u|ū) Otago",
      "kelly tarlton's sea life aquarium",
      "routebum track",
      "fox glacier",
      "pukekura",
      "international antarctic centre",
      "rangitoto",
      "milford track",
      "otago peninsula",
      "hot water beach",
      "wakatipu",
      "te whanganui-a-hei",
      "aoraki",
      "mount cook",
      "zealandia",
      "christchurch",
      "waiheke",
      "waimangu",
      "kepler track",
      "mount maunganui",
      "orana wildlife park",
      "willowbank wildlife reserve",
      "waitomo glowworm caves",
      "wellington botanic garden",
      "waitemata harbour",
      "lake te anau",
      "hamilton gardens",
      "westland tai poutini",
      "wellington museum",
      "kauri museum",
      "whanganui",
    ],
    'ignore': [
      "eorge|willie\reggie|jj|major|liam|rogers) nelson|\b(beef|pork) wellington",
    ],
    "whitelist": [
      "nzbeer",
      "nelsonnz",
      "queenstown",
      "marton_nz",
      "eit",
      "palmy",
      "nznews",
      "nztravel",
      "nzcirclejerkcopypasta",
      "bayofplenty",
      "nzmodmaildrama",
      "kiwilol",
      "4wdnz",
      "nzmalefashionadvice",
      "nztikitour",
      "nzmetahub",
      "nzmusic",
      "truenewzealand",
      "newzealandproblems",
      "newzealandpics",
      "nzesg",
      "mtalbert",
      "auckland",
      "nzgaming",
      "hiphopnz",
      "cryptokiwis",
      "nzgreen",
      "winstonjerk",
      "taranaki",
      "nzbitcoin",
      "rangiora",
      "minecraftnz",
      "vuw",
      "percapitabragging",
      "christchurch",
      "newzealandparliament",
      "nzsports",
      "arovalley",
      "meta_new_zealand",
      "palmerstonnorth",
      "nztreeschch",
      "nzmigrants",
      "nzphotos",
      "truezealand",
      "nzatheism",
      "hawkesbay",
      "nzgonewild",
      "nzcreepshots",
      "kiwirock",
      "nuzilland",
      "nzredditisland",
      "greylynn",
      "nowellingtonhaircuts",
      "nzpolitics",
      "nzindoors",
      "newzealand",
      "kiwicaching",
      "dunedin",
      "nzcirclejerk",
      "nzfootball",
      "nzfightclub",
      "thetron",
      "notthecivilian",
      "nztf2",
      "universityofauckland",
      "srsnz",
      "theridges",
      "nzmovies",
      "gcsbbill",
      "aleague",
      "newzealandfilm",
      "nzmusicians",
      "nzconfessions",
      "nzwizards",
      "nzfood",
      "nzcringe",
      "lolnewzealand",
      "nzdepthhub",
      "rcnz",
      "kokako",
      "nztv",
      "nztrees",
      "askakiwi",
      "nzsubredditdrama",
      "nzlgbt",
      "new_zealand",
      "nzknittingandcrochet",
      "ketonz",
      "holidaynewzealand",
      "truenz",
      "newtownrulz",
      "wellingtonhaircuts",
      "stewartisland",
      "aotearoa",
      "nzoutdoors",
      "newzealandhistory",
      "newzealandmusic",
      "shortlandstreet",
      "nzsucks",
      "destinychurch",
      "nzreggae",
      "nzforsale",
      "nzsecretsquirrel",
      "nzsubredditdramadrama",
      "thatpicofnzfromspace",
      "occupynz",
      "blenheim",
      "thealmightyjohnson",
      "nzmemes",
      "wellington",
      "chch",
      "nzfilm",
      "kiwitech",
    ],
    "blacklist": [
      "{'eliteracers'}",
    ],
  },
  {
    "name": "imagesofnorthcarolina",
    "search": [
      "north carolina",
    ],
    "whitelist": [
      "northcarolina",
    ],
  },
  {
    "name": "imagesofnorthdakota",
    "search": [
      "north dakota",
    ],
    'ignore': [
      "northdakota",
    ],
    "whitelist": [
      "northdakota",
    ],
  },
  {
    "name": "imagesofnorway",
    "search": [
      "norway",
    ],
    "whitelist": [
      "norwaypics",
      "norwayonreddit",
      "norway",
    ],
  },
  {
    "name": "imagesofohio",
    "search": [
      "ohio",
    ],
    "whitelist": [
      "ohio",
    ],
  },
  {
    "name": "imagesofoklahoma",
    "search": [
      "oklahoma",
    ],
    "whitelist": [
      "oklahoma",
    ],
  },
  {
    "name": "imagesoforegon",
    "search": [
      "oregon",
    ],
    'ignore': [
      "McCarthy(’s)? Oregon",
    ],
    "whitelist": [
      "oregon",
    ],
  },
  {
    "name": "imagesofpennsylvania",
    "search": [
      "pennsylvania",
    ],
    "whitelist": [
      "pennsylvania",
    ],
  },
  {
    "name": "imagesofperu",
    "search": [
      "peru",
      "lima",
      "cusco",
      "arequipa",
      "iquitos",
      "puno",
      "colca canyon",
      "Man(ú|u) National Park",
      "huaraz",
      "machu picchu",
      "sacred valley",
      "saksaywaman",
      "qurikancha",
      "Urubamba",
      "santa catalina monastery",
      "huayna picchu",
      "huaca pucllana",
    ],
    'ignore': [
      "lima bean",
    ],
    "whitelist": [
      "perupics",
      "peru",
    ],
  },
  {
    "name": "imagesofrhodeisland",
    "search": [
      "rhode island",
    ],
    "whitelist": [
      "rhodeisland",
    ],
  },
  {
    "name": "imagesofrussia",
    "search": [
      "russian?",
      "moscow",
      "saint petersburg",
      "lake baikal",
      "sochi",
      "vladivostok",
      "kaliningrad",
      "volgograd",
      "irkutsk",
      "kazan",
      "murmansk",
      "khabarovsk",
      "samara",
      "yekaterinburg",
      "sakhalin",
      "novosibirsk",
      "yakutsk",
      "veliky novgorod",
      "krasnoyarsk",
      "grozny",
      "omsk",
      "nizhny novgorod",
      "suzdal",
      "solovetsky islands?",
      "ufa",
      "magadan",
      "rostov\bon\bdon",
      "krasnodar",
      "tomsk",
      "ulan\bude",
      "norilsk",
      "chelyabinsk",
      "olkhon island",
      "petropavlovsk\bkamchatsky",
      "yuzhno\bsakhalinsk",
      "yaroslavl",
      "petro",
      "saratov",
      "voronezh",
      "tula",
      "tver",
      "tyumen",
      "izhevsk",
      "gelendzhik",
      "nakhodka",
      "oymyakon",
      "tolyatti",
    ],
    "whitelist": [
      "russiapics",
      "russia",
    ],
  },
  {
    "name": "imagesofscotland",
    "search": [
      "scotland",
      "edinburgh",
      "glasgow",
      "loch ness",
      "skye",
      "scottish highlands",
      "dundee",
      "islay",
      "aviemore",
      "loch lomond",
      "pitlochry",
      "callander",
      "gretna green",
      "inveraray",
      "ballater",
      "melrose",
      "drunkeld",
      "braemar",
      "leith",
      "aberfoyle",
      "falkirk",
      "barra",
      "killin",
      "cairngorms",
      "drumnadrochit",
      "peebles",
      "grantown-on-spey",
      "inverurie",
      "fort augustus",
      "luss",
      "aberfeldy",
      "newtonmore",
      "crieff",
      "castle douglas",
      "strathpeffer",
      "balloch",
      "lewis and harris",
      "auchterarder",
      "ballachulish",
      "rothesay",
      "edinburgh",
      "holyrood",
      "kelvingrove",
      "arthur's seat",
      "glasgow",
      "princes st(reet)?",
      "burrell collection",
      "s(ain)?t gile'?s cathedral",
      "falkirk wheel",
      "mary king'?s close",
      "urquhart",
      "melrose abbey",
      "kelvingrove park",
      "cairngorms",
      "blair drummond safari",
      "our dynamic earth",
      "hunterian museum",
      "mcmanus galleries",
      "wallace monument",
      "riverside museum",
      "culzean castle",
      "s(ain)?t andrews cathedral",
      "falkland palace",
      "broughty castle",
      "balmoral castle",
      "rosslyn chapel",
      "gleneagles hotel",
      "skara brae",
      "glamis castle",
      "sse hydro",
    ],
    "ignore_case": [
      "killin",
    ],
    "whitelist": [
      "scotland",
      "scottishphotos",
    ],
  },
  {
    "name": "imagesofsouthcarolina",
    "search": [
      "south carolina",
    ],
    'ignore': [
      "wv",
    ],
    "whitelist": [
      "columbiyeah",
      "greenwoodsc",
      "charleston",
      "florencesc",
      "greenville",
      "georgetownsc",
      "andersonsc",
      "westminstersc",
      "easley",
      "sumter",
      "spartanburg",
      "simpsonville",
      "powdersville",
      "rockhill",
      "newberry",
      "myrtlebeach",
      "southcarolina",
      "hiltonhead",
      "aiken",
      "unionsc",
    ],
  },
  {
    "name": "imagesofsouthdakota",
    "search": [
      "south dakota",
    ],
    "whitelist": [
      "southdakota",
    ],
  },
  {
    "name": "imagesofsyria",
    "search": [
      "syria",
      "damascus",
      "aleppo",
      "lattakia",
      "palmyra",
      "tartus",
      "kilis",
      "kessab",
      "al-raqqah",
      "al-zabadani",
      "homs",
      "as-suwayda",
      "baniyas",
      "hama",
      "masyaf",
      "marmarita",
      "bosra",
      "majdal shams",
      "safita",
      "nimrod fortress",
      "ayn al-arab",
      "mal'loula",
      "daraa",
      "deir ez-zor",
      "afrin",
      "idlib",
      "al-hasakah",
      "saidnaya",
      "al-qamishli",
      "sayyidah zaynab",
      "salah ed-din",
      "lake assad",
      "jaramana",
      "jableh",
      "yabroud",
      "harasta",
      "ras al-ayn",
      "al-hasakah governorate",
      "mashta al-helu",
      "lake homs",
      "yaafour",
    ],
    'ignore': [
      "damascus steel",
    ],
    "whitelist": [
      "syria",
      "syriancivilwar",
    ],
    "blacklist": [
      "{'bladesmith', 'knifemaking', 'knifeclub', 'knifeporn', 'knives'}",
    ],
  },
  {
    "name": "imagesoftennessee",
    "search": [
      "tennessee",
    ],
    "whitelist": [
      "tennessee",
    ],
  },
  {
    "name": "terlingua",
    "search": [
      "terlingua",
    ],
    "whitelist": [
      "null",
    ],
  },
  {
    "name": "imagesoftexas",
    "search": [
      "texas",
      "tx",
      "texans?",
      "austin",
      "dallas",
      "houston",
      "san antonio",
      "fo?r?t worth",
      "el paso",
      "arlington",
      "corpus christi",
      "plano",
      "laredo",
    ],
    'ignore': [
      "austin (powers|seven|taylor)",
    ],
    "whitelist": [
      "denton",
      "longviewtexas",
      "aclfestival",
      "austinpetlostandfound",
      "mavericks",
      "gptx",
      "huntsvilletexas",
      "tylertx",
      "austinclassifieds",
      "austinshows",
      "wichitafalls",
      "austinbeer",
      "texasguns",
      "houstonfood",
      "cedarcreek",
      "stthomas",
      "riograndevalley",
      "valley956",
      "deerpark",
      "utaustin",
      "theticket",
      "dfwgameswap",
      "brazoriacounty",
      "bigbendtx",
      "austintraffic",
      "houstonbeer",
      "queeraustin",
      "texas_classifieds",
      "kingwood",
      "texassouthern",
      "manor",
      "sxsw",
      "setxmusic",
      "austincomedy",
      "dfwgaymers",
      "austinbloggers",
      "newbraunfels",
      "austinstartups",
      "planotx",
      "houstonguns",
      "richardson",
      "lamaruniversity",
      "audirgv",
      "dfwjobs",
      "tomball",
      "austinphotography",
      "austinliving",
      "thewoodlands",
      "boerne",
      "atxmusic",
      "amarillo",
      "austinfood",
      "mineralwells",
      "mckinney",
      "atxpix",
      "txrenaissancefestival",
      "austinfrugal",
      "satx4satx",
      "sasaustin",
      "castroville",
      "roundrock",
      "austingreenbelt",
      "dallasmeetups",
      "austincarpangler",
      "abilene",
      "laketravis",
      "occupyaustin",
      "lewisville",
      "12thmanfootball",
      "wtamu",
      "clearlake",
      "dfwart",
      "laredo",
      "lubbockmusicians",
      "rgvstandup",
      "gayrgv",
      "semisaltyeggsinaustin",
      "setx",
      "corsicanatx",
      "austinisd",
      "r4rdfw",
      "austincc",
      "elpasobeer",
      "austinrp",
      "plano",
      "texas_reddirt",
      "austincitylimits",
      "austin",
      "austinrunning",
      "bikingatx",
      "dallasfood",
      "rockets",
      "utdallas",
      "pflugerville",
      "boyd",
      "texans",
      "boydhighschool",
      "flowermound",
      "texansff",
      "bastroptx",
      "dfwbike",
      "euless",
      "austinveg",
      "austincirclejerk",
      "houstonsoccer",
      "oakcliff",
      "austinmtg",
      "txstate",
      "trueaustin",
      "fulshear",
      "rentaustin",
      "houstonevents",
      "texasbeer",
      "midessa",
      "dfwroommates",
      "westtexas",
      "austingonewild",
      "astros",
      "utep",
      "whitesettlement",
      "texas",
      "dfwfilmmakers",
      "sxswi",
      "hillcountry",
      "carrolltontx",
      "jollyville",
      "austinsanantonio",
      "heartland",
      "depressionaustin",
      "askaustin",
      "helpmeaustin",
      "northwestvista",
      "westcentraltexas",
      "uiw",
      "conroe",
      "austinswap",
      "fcdallas",
      "houstonmusic",
      "springbranch",
      "southtexas",
      "friendswood",
      "austinevents",
      "keepaustinweird",
      "sanantoniofood",
      "edinburg",
      "dfwbeer",
      "forney",
      "austintrades",
      "austinrecsandreviews",
      "universityofhouston",
      "atxrecords",
      "cypresstx",
      "stephenville",
      "east_texas",
      "marfa",
      "austincannabis",
      "lubbocktx",
      "tcu",
      "nwatx",
      "houstonclassifieds",
      "bikesanantonio",
      "greenvilletx",
      "dallas",
      "belton",
      "brownwood_texas",
      "texastech",
      "lubbock",
      "dfw",
      "socialanxietyaustin",
      "truetexas",
      "riveroaks",
      "cityoflaredo",
      "texascountry",
      "sascorpionsfc",
      "shadownet",
      "texasrangers",
      "tamuc",
      "frisco",
      "atxrecsports",
      "houstonr4r",
      "longhorn",
      "livemusiccapital",
      "atascocita",
      "dallist",
      "dynamo",
      "austinshowlistings",
      "texaspolitics",
      "lubbockdogs",
      "dfwguns",
      "dfwgaming",
      "pearland",
      "uttrees",
      "dfwpets",
      "wilcocorruption",
      "bcstx",
      "austintrees",
      "uhlc",
      "austindogs",
      "austinclimbing",
      "sugarland",
      "lonestar",
      "roundrocktexas",
      "elpaso",
      "granbury",
      "highlandvillage",
      "riceuniversity",
      "easttx",
      "dallasstars",
      "tstcharlingen",
      "sanger",
      "katy",
      "irvingtexas",
      "austinmotorcycles",
      "texashistoryporn",
      "rockwall",
      "truedenton",
      "atxcommcollege",
      "katy_texas",
      "txrangersexpress",
      "easttexas",
      "acu",
      "pedicabatx",
      "txmoto",
      "utsa",
      "universityoftexas",
      "nbaspurs",
      "cedarpark",
      "barcraftaustin",
      "restorethefourthatx",
      "terlingua",
      "garland",
      "austinscience",
      "austents",
      "austinjobs",
      "fortworth",
      "aggies",
      "leander",
      "texents",
      "collincollege",
      "utarlington",
      "shsu",
      "austingaymers",
      "fireteamaustin",
      "austinjeeps",
      "atascocitatx",
      "copperascove",
      "dfwclassifieds",
      "waco",
      "sanmarcos",
      "bikehouston",
      "austinintrovertsocial",
      "jerseyvillage",
      "san_angelo",
      "roundrockexpress",
      "houstonjob",
      "unt",
      "kerrville",
      "baytown",
      "cowboys",
      "austinmusicians",
      "thecolony",
      "austinyoga",
      "austinguns",
      "smu",
      "lockhart",
      "houstonriders",
      "austintexas",
      "utbrownsville",
      "arlington",
      "dfwmarketplace",
      "texarkana",
      "austinpoker",
      "stedwards",
      "dfwmusic",
      "austinfilmmakers",
      "austin_metal",
      "longhornnation",
      "effaustin",
      "arlingtontx",
      "drippingsprings",
      "leandercedarpark",
      "baycitytx",
      "bigbend",
      "corpus",
      "paristexas",
      "austinents",
      "stmu",
      "bigbendnationalpark",
      "hurst",
      "benbrook",
      "austintxmusic",
      "allen",
      "palestinetx",
      "sanantonio",
      "atxgaybros",
      "texasskateboarding",
      "wimberley",
      "huntsvilletx",
      "utmemes",
      "katytx",
      "austinbiz",
      "alamocolleges",
      "houstonsocials",
      "atx4atx",
      "collegestation",
      "atxlostandfound",
      "bitcoinaustin",
      "funfunfunfest",
      "houstonents",
      "killeen",
      "paristx",
      "gasmonkey",
      "eastsidechess",
      "texashistory",
      "dallasriders",
      "weatherford",
      "fortbend",
      "austindiscgolf",
      "commercetx",
      "trinityu",
      "portaransas",
      "atxgooglefiber",
      "northtexas",
      "abilenetexas",
      "houston",
      "coogshouse",
      "keller",
      "aransaspass",
      "marblefalls",
      "baylor",
      "georgetowntx",
      "texasfavors",
      "tccstudentsconnect",
      "galveston",
      "uhd",
      "texaschl",
      "austinkids",
      "collegestationbeer",
      "heidenheimer",
      "corpuschristi",
      "austinurbex",
    ],
    "blacklist": [
      "{'virginia', 'nova'}",
    ],
  },
  {
    "name": "imagesoftoronto",
    "search": [
      "toronto",
    ],
    "whitelist": [
      "torontourbanfishing",
      "torontocraftbeer",
      "tfc",
      "toronto",
      "georgebrowncollege",
      "frugalto",
      "torontojobs",
      "torontodriving",
      "totrees",
      "torontocityhall",
      "humber",
      "yorku",
      "brampton",
      "fishingontario",
      "uoft",
      "torontotransit",
      "torontobiking",
      "torontorenting",
      "torontoraptors",
      "torontoart",
      "torontobluejays",
      "torontorealestate",
      "torontoparks",
      "volunteertoronto",
      "tofoodie",
      "ryerson",
      "foodtoronto",
      "leafs",
      "tomaps",
    ],
  },
  {
    "name": "imagesofusa",
    "search": [
      "usa",
      "american?s?",
      "murica",
      "united states",
    ],
    'ignore': [
      "orth|central|south|captain) (america|murica)|\bamerican cheese",
    ],
    "whitelist": [
      "unitedstatesofamerica",
    ],
  },
  {
    "name": "imagesofutah",
    "search": [
      "utah",
    ],
    "whitelist": [
      "utah",
    ],
  },
  {
    "name": "imagesofvermont",
    "search": [
      "vermont",
    ],
    "whitelist": [
      "vermont",
    ],
  },
  {
    "name": "imagesofvirginia",
    "search": [
      "virginia",
    ],
    'ignore': [
      "west virginia",
    ],
    "whitelist": [
      "virginia",
    ],
  },
  {
    "name": "imagesofwales",
    "search": [
      "wales",
      "conwy castle",
      "bodnant garden",
      "big pit national coal museum",
      "snowdon",
      "llechwedd slate caverns",
      "castell coch",
      "dan yr ogof",
      "snowdon mountain railway",
      "national slate museum",
      "national roman legion museum",
      "pontcysyllte aqueduct",
      "powis castle",
      "pembroke castle",
      "oakwood theme park",
      "pen y fan",
      "dinorwig power station",
      "tredegar house",
      "syngun copper mine",
      "dinefwr castle",
      "harlech castle",
      "celtic manor resort",
      " cadair idris",
      "tryfan",
      "crib goch",
      "llangollen canal",
      "coed-y-brenin",
      "moel famau",
      "chirk castle",
      "pen-y-pass",
      "glyder fawr",
      "monmouthshire",
      "pistyll raeadr",
      "whitesands bay",
      "grand theatre",
      "goodrich castle",
      "llangollen railway",
      "puzzlewood",
      "clearwell caves",
      "sgwd henrhyd",
      "blue lagoon waterpark",
      "swallow falls",
      "glyder fach",
      "erddig",
      "horseshoe pass",
      "lc swansea",
      "dyffryn gardens",
      "llanberis lake railway",
      "castell dinas br(a|â)n",
      "swansea",
      "brecon",
      "pembrokeshire",
      "bridgend",
      "llangollen",
      "betws-y-coed",
      "wrexham",
      "bala",
      "monmouth",
      "llanberis",
      "portmeirion",
      "dolgellau",
      "dardigan",
      "abergavenny",
      "blaenau ffestiniog",
      "black mountains",
      "beddgelert",
      "harlech",
      "welshpool",
      "caerphilly",
      "llandovery",
      "crickhowell",
      "machynlleth",
      "llanfairpwllgwyngyll",
      "ruthin",
      "skomer",
      "llangors",
      "ffestiniog",
      "st clears",
      "merthyr tydfil",
      "ebbw vale",
      "pontypridd",
      "aberdare",
      "pendine",
      "llandeilo",
      "rhossili",
      "llandrindod wells",
      "capel curig",
      "narberth",
      "llanbedr",
      "blaenavon",
      "ystradgynlais",
      "treforest",
      "aberdaron",
      "risca",
      "pontypool",
    ],
    'ignore': [
      "blackpool",
    ],
    "whitelist": [
      "wales",
    ],
  },
  {
    "name": "imagesofwashington",
    "search": [
      "washington",
    ],
    'ignore': [
      "d\.?c\.?",
    ],
    "whitelist": [
      "washington",
      "mount_rainier",
    ],
  },
  {
    "name": "imagesofwashingtondc",
    "search": [
      "washington dc",
      "district of columbia",
      "white house",
      "national mall",
      "unites states capitol",
      "lincoln memorial",
      "national museum of natural history",
      "national zoological park",
      "national air and space museum",
      "vietnam veterans memorial",
      "washington monument",
      "thomas jefferson memorial",
      "united states holocaust memorial",
      "international spy museum",
      "national world war ii memorial",
      "newseum",
      "smithsonian",
      "washington national cathedral",
      "ford's theatre",
      "korean war veterans memorial",
      "john f\.? kennedy center for the performing arts",
      "franklin delano roosevelt memorial",
      "united states botanic garden",
      "madame tussauds washington",
      "national portrait gallery",
      "national archives",
      "national building museum",
      "hirshhorn museum and sculpture",
      "the phillips collection",
      "united states national arboretum",
      "national museum of african art",
      "national museum of crime",
      "national postal museum",
      "renwick gallery",
      "hillwood estate",
      "basilica of the national shrine of the immaculate conception",
      "freer gallery of art",
      "corcoran gallery of art",
      "anacostia community museum",
      "united states capitol visitor center",
      "arts and industries building",
      "tudor place",
      "arthur m\.? sackler gallery",
      "folger shakespeare library",
      "organization of american states",
      "9:30 club",
      "national academy of sciences",
    ],
    'ignore': [
      "polish national archives",
    ],
    "whitelist": [
      "dcphotography",
      "washingtondc",
    ],
  },
  {
    "name": "imagesofwestvirginia",
    "search": [
      "west virginia",
      "w virginia",
      "WV\b|pipestem resort",
      "charleston",
      "morgantown",
      "harpers ferry",
      "coopers rock state forest",
      "huntington",
      "new river gorge",
      "canaan valley",
      "white sulphur springs",
      "elkins",
      "snowshoe",
      "fayetteville",
      "moundsville",
      "blackwater falls",
      "wheeling",
      "oak hill",
      "seneca rocks",
      "charles town",
      "cass",
      "parkersburg",
      "fairmont",
      "blennerhassett island",
      "lewisburg",
      "beckley",
      "williamstown",
      "north bend state park",
      "greenbrier river trail",
      "babcock",
      "bridgeport",
      "harpers ferry national historical park",
      "martinsburg",
      "buckhannon",
      "clarksburg",
      "camp creek state park",
      "watoga state park",
      "bluefield",
      "bramwell",
      "lost river",
      "point pleasant",
      "roanoke",
      "shepherdstown",
      "monongahela",
      "barboursville",
      "marlinton",
    ],
    'ignore': [
      "rosie huntington.whiteley",
    ],
    "ignore_case": [
      "wheeling",
    ],
    "whitelist": [
      "westvirginia",
    ],
    "blacklist": [
      "{'hdm_stuttgart', 'charleston', '4x4'}",
    ],
  },
  {
    "name": "imagesofwisconsin",
    "search": [
      "wisconsin",
      "wisc",
      "green bay\b(?!.packers|gamblers)|\bmilwaukee\b(?!.brewers|bucks)|\bnew glarus",
      "spotted cow",
      "msoe",
      "summerfest",
      "door county",
      "fox valley",
      "lake winnebago",
      "house on the rock",
      "cave on the mound.?",
      "harley.davidson museum",
      "devil's lake state park",
      "kettle moraine",
      "sturgeon bay",
      "appleton",
      "eau claire",
      "minocqua",
      "eagle river",
      "egg harbor",
      "stevens point",
      "fond du lac",
      "lambeau field",
      "eaa airventure",
      "eaa air venture",
      "miller park",
      "pabst theater",
      "alpine valley",
      "eaa\b.*\boshkosh",
      "oshkosh\b.*\beaa",
      "(uw.oshkosh|uw.madison)",
      "madison\b.*\bwi.*",
      "mke",
      "scott walker",
      "gov(\.|ernor)? walker",
    ],
    'ignore': [
      "wisconsin ave.*",
    ],
    "whitelist": [
      "uwstout",
      "wausau",
      "matc",
      "manitowoc",
      "madisonwi",
      "wisconsin",
      "lacrossewi",
      "wisconsinbadgers",
      "miad",
      "wisconsinfishing",
      "northernwi",
      "foxvalleywi",
      "hudsonwi",
      "racine",
      "greenwisconsin",
      "doorcounty",
      "wisconsinbeer",
      "waukeshacounty",
      "msoe",
      "paddlewisconsin",
      "greenbay",
      "kenosha",
      "madisonmusic",
      "oshkosh",
      "uwmadison",
      "uwmilwaukee",
      "chequamegon_bay_wi",
      "eau_claire",
      "mequon",
      "motorcyclewisconsin",
      "marquette",
      "riverfallswi",
      "uwsp",
      "wisconsinpolitics",
      "uwl",
      "janesville",
      "westallis",
      "uwplatteville",
      "sheboygan",
      "uwwhitewater",
      "fonddulac",
      "uweaauclaire",
      "uwm",
      "milwaukee",
      "wauwatosa",
    ],
    "blacklist": [
      "{'tattoos', 'trees'}",
    ],
  },
  {
    "name": "imagesofwyoming",
    "search": [
      "wyoming\b\|\bwy",
      "yellowstone",
      "grand teton",
      "laramie",
      "teton village",
      "jackson lake",
      "rawlins",
      "rock springs",
      "devils tower",
      "thermopolis",
      "moran",
      "evanston",
      "jenny lake",
      "boysen reservoir",
      "lander",
      "riverton",
      "colter bay",
      "glendo state park",
      "green river",
      "dubois",
      "torrington",
      "signal (mountain|mtn)",
      "guernsey state park",
      "lusk",
      "greybull",
      "saratoga",
      "keyhole state park",
      "worland",
      "sinks canyon",
      "shoshoni",
      "pine bluffs",
      "bighorn national forest",
      "guernsey",
      "pinedale",
      "newcastle",
      "old faithful",
    ],
    'ignore': [
      "newcastle united",
    ],
    "ignore_case": [
      "lander",
    ],
    "whitelist": [
      "wyoming",
    ],
  },
  {
    "name": "imagesofyemen",
    "search": [
      "yemen",
      "Yemenis?",
      "Socotra",
      "Sana'a",
      "aden",
      "Shibam",
      "Al Hudaydah",
      "Ghumdan Palace",
      "Cisterns of Tawila",
      "Sheba Palace",
    ],
    "whitelist": [
      "yemen",
      "yemenpics",
      "yemenicrisis",
    ],
  },
]
